### ISSUE TITLE
_reflns.B_iso_Wilson_estimate present in phenix output

### ISSUE THREAD

**Issue by wtempel** [berrisfordjohn/adding_stats_to_mmcif#12]
.. interferes, under current wwpdb validation, with addition of other items in the '_reflns.' category. Speculation: wwpdb validation claims duplication of the category even though no actual items are duplicated, but the category's items may be dispersed throughout the cif block. Would such dispersion actually violate the format definition?

**Comment by berrisfordjohn** [comment]
mmCIF category will be merged if the items are unique between two instances and the number of values are the same - handled in version 0.3
